spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: security,database
app:
    frontend:
      url: http://localhost:5173

logging:
  level:
    root: INFO
    com.pethelper: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG